
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///test_spring
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false